himall_v2.8_ms/Himall.Web/Areas/Admin/Controllers/AgreementController.cs
using Himall.IServices;
using Himall.Model;
using Himall.Web.Framework;
using Himall.Web.Models;
using System;
using System.Web.Mvc;
using Himall.Application;
using System.Drawing;
using System.IO;

namespace Himall.Web.Areas.Admin.Controllers
{
    public class AgreementController : BaseAdminController
    {
        ISystemAgreementService _iSystemAgreementService;
        public AgreementController(ISystemAgreementService iSystemAgreementService)
        {
            _iSystemAgreementService = iSystemAgreementService;
        }
        // GET: Admin/Agreement
        public ActionResult Management()
        {
            var AgreementTypes = Himall.Model.AgreementInfo.AgreementTypes.Buyers;
            if (!string.IsNullOrEmpty(Request.QueryString["type"]) && Request.QueryString["type"].Equals("Seller"))
            {
                AgreementTypes = Himall.Model.AgreementInfo.AgreementTypes.Seller;
            }
            //初始化默认返回买家注册协议
            return View(GetManagementModel(AgreementTypes));
        }
        /// <summary>
        /// 入驻链接
        /// </summary>
        /// <returns></returns>
        public ActionResult SettledLink()
        {
            #region 商家入驻链接和二维码
            string LinkUrl = String.Format("http://{0}/m-weixin/shopregister/step1", Request.Url.Authority);
            ViewBag.LinkUrl = LinkUrl;
            string qrCodeImagePath = string.Empty;
            if (!string.IsNullOrWhiteSpace(LinkUrl))
            {
                Bitmap map;
                map = Core.Helper.QRCodeHelper.Create(LinkUrl);
                MemoryStream ms = new MemoryStream();
                map.Save(ms, System.Drawing.Imaging.ImageFormat.Bmp);
                qrCodeImagePath = "data:image/gif;base64," + Convert.ToBase64String(ms.ToArray()); // 将图片内存流转成base64,图片以DataURI形式显示  
                ms.Dispose();
            }
            ViewBag.Imgsrc = qrCodeImagePath;
            #endregion
            return View();
        }

        public ActionResult EnterSet()
        {
            //入驻参数设置
            return View();
        }


        [HttpPost]
        public JsonResult GetManagement(int agreementType)
        {
            return Json(GetManagementModel((Himall.Model.AgreementInfo.AgreementTypes)agreementType));
        }

        public AgreementModel GetManagementModel(Himall.Model.AgreementInfo.AgreementTypes type)
        {
            AgreementModel model = new AgreementModel();
            var iAgreement = _iSystemAgreementService.GetAgreement(type);
            model.AgreementType = iAgreement.AgreementType;
            model.AgreementContent = iAgreement.AgreementContent;
            return model;

        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult UpdateAgreement(int agreementType, string agreementContent)
        {
            var iAgreement = _iSystemAgreementService;
            AgreementInfo model = iAgreement.GetAgreement((Himall.Model.AgreementInfo.AgreementTypes)agreementType);
            model.AgreementType = agreementType;
            model.AgreementContent = agreementContent;
            if (iAgreement.UpdateAgreement(model))
                return Json(new Result() { success = true, msg = "更新协议成功！" });
            else
                return Json(new Result() { success = false, msg = "更新协议失败！" });
        }

        #region 入驻设置
        public ActionResult Settled()
        {
            var model = ShopApplication.GetSettled();
            return View(model);
        }


        /// <summary>
        /// 商家入驻设置
        /// </summary>
        /// <param name="mSettled"></param>
        /// <returns></returns>
        public JsonResult setSettled(Himall.DTO.Settled mSettled)
        {
            ShopApplication.Settled(mSettled);
            return Json(new Result() { success = true, msg = "设置成功！" });
        }

        #endregion
    }
}

himall_v2.8_ms/Himall.Web/Areas/Web/Controllers/InstallerController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Configuration;
using System.Text.RegularExpressions;
using System.Data;
using System.Web.Configuration;
using System.IO;
using System.Data.SqlClient;
using System.Data.Common;
using System.Text;
using System.Globalization;
using MySql.Data.MySqlClient;
using System.Xml;
using Himall.Core;

namespace Himall.Web.Areas.Web.Controllers
{
    public class InstallerController : Controller
    {
        private IList<string> errorMsgs = null;
        private int usernameMinLength = 3;
        private int usernameMaxLength = 20;
        private string usernameRegex = "[\u4e00-\u9fa5a-zA-Z0-9]+[\u4e00-\u9fa5_a-zA-Z0-9]*";
        private int passwordMaxLength = 16;
        private int passwordMinLength = 6;


        string _dbServer,                       // 数据库服务器
         _dbPort,
         _dbName,                        // 数据库名称
         _dbLoginName,             // 数据库登录名
         _dbPwd,                          // 数据库密码
         _siteName,                     //  网站名称
         _siteAdminName,         //  管理员名称
         _sitePwd,                       //  管理员密码
         _sitePwd2,                       //  管理员密码
         _shopName,                 //  官方自营店名称
         _shopAdminName,     //  官方自营店管理员名称
         _shopPwd,                      // 官方自营店密码
        _shopPwd2;                      // 官方自营店密码

        private bool IsInstalled()
        {
            var t = ConfigurationManager.AppSettings["IsInstalled"];
            return null == t || bool.Parse(t);
        }

        string GetPasswrodWithTwiceEncode(string password, string salt)
        {
            //string encryptedPassword = Core.Helper.SecureHelper.MD5(password);//一次MD5加密
            //string encryptedWithSaltPassword = Core.Helper.SecureHelper.MD5(encryptedPassword + salt);//一次结果加盐后二次加密
            //return encryptedWithSaltPassword;
            return Himall.Core.Helper.SecureHelper.MD5(Himall.Core.Helper.SecureHelper.MD5(password) + salt);
        }

        // GET: Web/Installer
        public ActionResult Agreement()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SaveConfiguration(string dbServer, string dbName, string dbLoginName, string dbPwd, string siteName, string siteAdminName, string sitePwd, string sitePwd2, string shopName, string shopAdminName, string shopPwd, string shopPwd2, int installData)
        {
            if (this.IsInstalled())
            {
                return base.Json(new { success = true, msg = "软件已经安装,不需要重新安装.", status = 0 }, JsonRequestBehavior.AllowGet);
            }
            this._dbServer = dbServer;                      // 数据库服务器
            this._dbPort = "";                              //string dbPort,                          //数据库端口
            this._dbName = dbName;
            this._dbLoginName = dbLoginName;                // 数据库名称
            this._dbPwd = dbPwd;                          // 数据库密码
            this._siteName = siteName;                     //  网站名称
            this._siteAdminName = siteAdminName;         //  管理员名称
            this._sitePwd = sitePwd;                       //  管理员密码
            this._sitePwd2 = sitePwd2;                       //  管理员密码
            this._shopName = shopName;                 //  官方自营店名称
            this._shopAdminName = shopAdminName;     //  官方自营店管理员名称
            this._shopPwd = shopPwd;                      // 官方自营店密码
            this._shopPwd2 = shopPwd2;                      // 官方自营店密码
            string msg = string.Empty;
            // 检查用户信息
            if (!this.ValidateUser(out msg))
            {
                return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
            }
            //创建数据库
            if (!this.CreateDtabase(out msg))
            {
                return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
            }
            //如果还没有运行过安装测试，则先运行安装测试
            if (!this.ExecuteTest())
            {
                return base.Json(new { success = true, errorMsg = "数据库链接信息有误" }, JsonRequestBehavior.AllowGet);
            }
            //检查权限
            if (!this.TestPermission())
            {
                return base.Json(new { success = true, errorMsg = "WEB目录读写权限不够." }, JsonRequestBehavior.AllowGet);
            }
            //执行数据脚本
            if (!this.CreateDataSchema(out msg))
            {
                return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
            }
            //创建管理员账户
            if (!this.CreateAdministrator(out msg))
            {
                return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
            }
            //添加演示数据
            if (installData == 1)
            {
                if (!this.AddDemoData(out msg))
                {
                    return base.Json(new { success = true, errorMsg = "添加演示数据失败" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                // 添加初始化数据
                if (!this.AddInitData(out msg))
                {
                    return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
                }
                if (!this.UpdateSliderImage(out msg))
                {
                    return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
                }
            }
            // 保存web.config文件
            if (!this.SaveConfig(out msg))
            {
                return base.Json(new { success = true, errorMsg = msg }, JsonRequestBehavior.AllowGet);
            }
            //服务配置
            this.SetServicesConfig(dbName);
            return base.Json(new { success = true, msg = "安装成功", status = 1 }, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 设置服务名称
        /// </summary>
        /// <param name="ServiceSuffix"></param>
        private void SetServicesConfig(string ServiceSuffix)
        {
            try
            {
                KeyValueConfigurationElement servicePathKey = WebConfigurationManager.OpenWebConfiguration(base.Request.ApplicationPath).AppSettings.Settings["ServicePath"];
                string serviceMainPath = "系统服务";
                if ((servicePathKey != null) && (servicePathKey.Value != ""))
                {
                    serviceMainPath = servicePathKey.Value;
                }
                string siteMapPath = base.Server.MapPath(base.Request.ApplicationPath);
                serviceMainPath = Path.Combine(siteMapPath, serviceMainPath);
                //根据配置文件里定义的服务路径，设置服务的服务名
                string path = Path.Combine(siteMapPath, "ServicePathSetting.xml");
                if (System.IO.File.Exists(path))
                {
                    XmlDocument document = new XmlDocument();
                    document.Load(path);
                    XmlNodeList nodelist = document.SelectNodes("ServiceConfig/Service");
                    string configPath = string.Empty;
                    //循环所有服务
                    for (int i = 0; i < nodelist.Count; i++)
                    {
                        string innerText;
                        XmlNode serviceConfigFileNode = nodelist.Item(i);
                        XmlNodeList configfileNodes = serviceConfigFileNode.SelectNodes("configfile");
                        if (configfileNodes.Count > 0)
                        {
                            innerText = configfileNodes.Item(0).InnerText;
                            configPath = Path.Combine(serviceMainPath, innerText);
                            //设置服务名后辍
                            SaveServiceName(configPath, ServiceSuffix);
                        }
                        XmlNodeList connconfigfileNodes = serviceConfigFileNode.SelectNodes("connconfigfile");
                        if (connconfigfileNodes.Count > 0)
                        {
                            innerText = connconfigfileNodes.Item(0).InnerText;
                            configPath = Path.Combine(serviceMainPath, innerText);
                            //设置服务数据库连接
                            SaveServiceMySqlConnection(configPath);
                        }
                    }
                }
            }
            catch (Exception exception)
            {
                Log.Error("设置服务名时出错(SetServicesConfig):" + exception.Message);
            }
        }
        /// <summary>
        /// 保存服务
        /// </summary>
        /// <param name="configPath">配置路径</param>
        /// <param name="serviceSuffix">后缀</param>
        private void SaveServiceName(string configPath, string serviceSuffix)
        {
            string str = configPath;
            if (!string.IsNullOrWhiteSpace(str))
            {
                XmlDocument document = new XmlDocument();
                if (System.IO.File.Exists(str))
                {
                    document.Load(str);
                    XmlNode node = document.SelectSingleNode("Settings/ServiceName");
                    if (node != null)
                    {
                        node.InnerText = serviceSuffix;
                    }
                    node = document.SelectSingleNode("Settings/DisplayName");
                    if (node != null)
                    {
                        node.InnerText = serviceSuffix;
                    }
                    node = document.SelectSingleNode("Settings/Description");
                    if (node != null)
                    {
                        node.InnerText = serviceSuffix;
                    }
                    document.Save(str);
                }
            }

        }
        /// <summary>
        /// 保存mysql数据库链接
        /// </summary>
        /// <param name="configPath"></param>
        private void SaveServiceMySqlConnection(string configPath)

himall_v2.8_ms/Himall.Web/Areas/Web/Views/Installer/Agreement.cshtml
@{
    ViewBag.Title = "Agreement";
    this.Layout = null;
}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>系统安装向导</title>
    <link href="~/Content/installStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.nicescroll.min.js"></script>
    <script>
$(function(){
	if(+[1,]){
		$(".agreement").niceScroll({
			cursorcolor:"#7B7C7E",
			cursorwidth:6,
		});
	}
});
    </script>
</head>

<body>
    <div class="warp">
        <div class="header cl">
            <div class="logo"><img src="/Images/installLogo.png" /></div>
            <div class="version">2017.07.31.01</div>
        </div>
        <div class="proess cl">
            <div class="cur">安装协议</div>
            <span class="cur"></span>
            <div>创建数据</div>
            <span></span>
            <div>安装完成</div>
        </div>
        <div class="content">
            <div class="agreement">
                <h3>Hishop Himall多用户商城安装向导</h3>
                <p>尊敬的用户，欢迎您注册成为本网站用户。在注册前请您仔细阅读如下服务条款：</p>
                <p>　　本服务协议双方为本网站与本网站用户，本服务协议具有合同效力。</p>
                <p>　　您确认本服务协议后，本服务协议即在您和本网站之间产生法律效力。请您务必在注册之前认真阅读全部服务协议内容，如有任何疑问，可向本网站咨询。</p>
                <p>　　无论您事实上是否在注册之前认真阅读了本服务协议，只要您点击协议正本下方的"注册"按钮并按照本网站注册程序成功注册为用户，您的行为仍然表示您同意并签署了本服务协议。</p>
                <p>1．本网站服务条款的确认和接纳</p>
                <p>　　本网站各项服务的所有权和运作权归本网站拥有。</p>
                <p>2．用户必须：</p>
                <p>　　(1)自行配备上网的所需设备， 包括个人电脑、调制解调器或其他必备上网装置。</p>
                <p>　　(2)自行负担个人上网所支付的与此服务有关的电话费用、 网络费用。</p>
                <p>3．用户在本网站上交易平台上不得发布下列违法信息：</p>
                <p>(1)反对宪法所确定的基本原则的；</p>
                <p>(2).危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</p>
                <p>(3).损害国家荣誉和利益的；</p>
                <p>(4).煽动民族仇恨、民族歧视，破坏民族团结的；</p>
                <p>(5).破坏国家宗教政策，宣扬邪教和封建迷信的；</p>
                <p>(6).散布谣言，扰乱社会秩序，破坏社会稳定的；</p>
                <p>(7).散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</p>
                <p>(8).侮辱或者诽谤他人，侵害他人合法权益的；</p>
                <p>(9).含有法律、行政法规禁止的其他内容的。</p>
                <p>4． 有关个人资料</p>
                <p>用户同意：</p>
                <p>(1) 提供及时、详尽及准确的个人资料。</p>
                <p>(2).同意接收来自本网站的信息。</p>
                <p>(3) 不断更新注册资料，符合及时、详尽准确的要求。所有原始键入的资料将引用为注册资料。</p>
                <p>(4)本网站不公开用户的姓名、地址、电子邮箱和笔名，以下情况除外：</p>
                <p>　　（a）用户授权本网站透露这些信息。</p>
                <p>　　（b）相应的法律及程序要求本网站提供用户的个人资料。如果用户提供的资料包含有不正确的信息，本网站保留结束用户使用本网站信息服务资格的权利。</p>
                <p>5.  用户在注册时应当选择稳定性及安全性相对较好的电子邮箱，并且同意接受并阅读本网站发往用户的各类电子邮件。如用户未及时从自己的电子邮箱接受电子邮件或  因用户电子邮箱或用户电子邮件接收及阅读程序本身的问题使电子邮件无法正常接收或阅读的，只要本网站成功发送了电子邮件，应当视为用户已经接收到相关的电  子邮件。电子邮件在发信服务器上所记录的发出时间视为送达时间。</p>
                <p>6． 服务条款的修改</p>
                <p>　　本网站有权在必要时修改服务条款，本网站服务条款一旦发生变动，将会在重要页面上提示修改内容。如果不同意所改动的内容，用户可以主动取消获得的本网站信息服务。如果用户继续享用本网站信息服务，则视为接受服务条款的变动。</p>
            </div>
            <div class="btn-group">
                <a href="@Url.Action("Configuration","Installer")" class="btn">同意协议进入安装</a><a class="btn disabled">不同意</a>
            </div>
        </div>
        <div class="footer">
            <p><strong>Powered By <span>Hishop</span>【Himall】</strong></p>
            <p>Copyright 2003 - 2017 Hishop网店系统 All Rights Reserved.</p>
            <p>软件注册备案号：234234234</p>
        </div>
    </div>
</body>
</html>

himall_v2.8_ms/Himall.Web/Areas/Web/Views/Installer/Completed.cshtml
@{
    ViewBag.Title = "Completed";
    this.Layout = null;
}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>系统安装向导-数据填写</title>
    <link href="~/Content/installStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.nicescroll.min.js"></script>
</head>

<body>
    <div class="warp">
        <div class="header cl">
            <div class="logo"><img src="/Images/installLogo.png" /></div>
            <div class="version">2015.07.21.02</div>
        </div>
        <div class="proess cl">
            <div class="cur">安装协议</div>
            <span class="finish"></span>
            <div class="cur">创建数据</div>
            <span class="finish"></span>
            <div class="cur">安装完成</div>
        </div>
        <div class="content">
            <div class="succeed"><span>√</span>恭喜，安装完成！</div>
            <div class="btn-group succeed-btn">
                <a href="/" class="btn">商城首页</a><a href="@Url.Action("Index","Home",new{area="Admin"})" class="btn">平台登录</a>
            </div>
        </div>
        <div class="footer">
            <p><strong>Powered By <span>Hishop</span>【Himall】</strong></p>
            <p>Copyright 2003 - 2014 Hishop网店系统 All Rights Reserved.</p>
            <p>软件注册备案号：234234234</p>
        </div>
    </div>
</body>
</html>